version: '3'
services:
 
  certbot:
    image: certbot/certbot
    container_name: h_certbot
    ports: 
      - "8282:80"
      - "4434:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      resources:
        limits:
          memory: 100M

  nginx:
    image: nginx:1.16-alpine
    container_name: h_nginx
    network_mode: host
    volumes:
      - ./data/static/html:/usr/share/nginx/html
      - ./data/static/sites/sites-enabled:/etc/nginx/sites-enabled
      - ./data/static/sites/sites-available:/etc/nginx/sites-available
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      resources:
        limits:
          memory: 150M
